### ISSUE TITLE
Put default text in UX search bar

### ISSUE THREAD

**Issue by Liard-Thomas** [ubikingenierie/ulp-observability-plugin#54]
Put "Graphs filters" in the search bar if nothing is present.

**Comment by Liard-Thomas** [comment]
@pmouawad Do i need to put "averages" instead of "thread_group" even in the metrics exposed by the backend, or do I just change the label in the front ? If i don't change it in the backend metrics, a Prometheus user might be confused because the label "thread_group" in the metrics would not be the same as the one in the front any more.

**Comment by pmouawad** [comment]
@Liard-Thomas  on both
