### ISSUE TITLE
Web dashboard improvements

### ISSUE THREAD

**Issue by pmouawad** [ubikingenierie/ulp-observability-plugin#72]
- [x] Add unit (ms) for response times
- [x] Average response => Average response times
- [x] Max response => Max response times

**Comment by Liard-Thomas** [comment]
What do you mean by 'Add unit (ms) for response times' ?
Do i add '(ms)' after each of the followings titles ? :
- Average response times
- Max response times
- Response percentiles (50th in ms)

**Comment by Liard-Thomas** [comment]
@pmouawad
